import type { Employee, Job } from "./jobflow-types";

export const mockEmployees: Employee[] = [
  { id: "emp-1", name: "John Doe", position: "Project Manager" },
  { id: "emp-2", name: "Jane Smith", position: "Technician" },
  { id: "emp-3", name: "Michael Cruz", position: "Developer" },
  { id: "emp-4", name: "Sarah Garcia", position: "Designer" },
];

export const mockJobs: Job[] = [
  {
    id: "job-1",
    title: "Replace HVAC filters — Building B",
    description: "Quarterly maintenance. Order filters before the site visit.",
    assignedEmployee: "emp-2",
    dueDate: "2026-10-03",
    priority: "high",
    status: "in_progress",
    createdAt: "2026-09-18T09:12:00.000Z",
  },
  {
    id: "job-2",
    title: "Client onboarding pack — Northwind",
    description: "Compile contract, timeline and contact sheet.",
    assignedEmployee: "emp-1",
    dueDate: "2026-09-30",
    priority: "medium",
    status: "todo",
    createdAt: "2026-09-20T13:40:00.000Z",
  },
  {
    id: "job-3",
    title: "Fix invoice export bug",
    description: "CSV export drops the tax column for multi-currency invoices.",
    assignedEmployee: "emp-3",
    dueDate: "2026-09-29",
    priority: "high",
    status: "in_progress",
    createdAt: "2026-09-22T08:05:00.000Z",
  },
  {
    id: "job-4",
    title: "Refresh service request form UI",
    description: "Apply the new field spacing and error states.",
    assignedEmployee: "emp-4",
    dueDate: "2026-10-09",
    priority: "low",
    status: "todo",
    createdAt: "2026-09-23T15:30:00.000Z",
  },
  {
    id: "job-5",
    title: "Site survey — Riverside depot",
    description: "Measure access routes and photograph the loading bay.",
    assignedEmployee: "emp-2",
    dueDate: "2026-09-25",
    priority: "medium",
    status: "complete",
    createdAt: "2026-09-10T11:00:00.000Z",
  },
  {
    id: "job-6",
    title: "Q3 job costing review",
    description: "Compare quoted vs actual hours across completed jobs.",
    assignedEmployee: "emp-1",
    dueDate: "2026-10-15",
    priority: "low",
    status: "todo",
    createdAt: "2026-09-24T10:20:00.000Z",
  },
  {
    id: "job-7",
    title: "Update team handbook assets",
    description: "New logo lockups and cover pages.",
    assignedEmployee: "emp-4",
    dueDate: "2026-09-26",
    priority: "medium",
    status: "complete",
    createdAt: "2026-09-08T14:45:00.000Z",
  },
];
